### Environment constants 

LGW_PATH ?= ../../lora_gateway/libloragw
ARCH ?=
CROSS_COMPILE ?=
export

### general build targets

all:
	$(MAKE) all -e -C lora_pkt_fwd

clean:
	$(MAKE) clean -e -C lora_pkt_fwd

### EOF
